---
#-------------------------------
# General Site Settings

title: sjnv20
logo:
author: themefisher
description: this is meta description
email: Lsjnv20@gmail.com
phone: 010 . 9196 . 6459
address: ì„œìš¸íŠ¹ë³„ì‹œ ê´€ì•…êµ¬ ì€ì²œë¡œ
copyright: Copyright &copy; 2020 Designed by Themefisher & Developed by Getjekyllthemes


menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi, I am Seonju
  hero-content: Frontend developer
  hero-fill: ì•ˆë…•í•˜ì„¸ìš” :)<br>ì–´ë””ì„œë“  ë‹¹ë‹¹í•˜ê²Œ ì œ ì—­ëŸ‰ì„ ì–´í•„í•  ìˆ˜ ìˆë„ë¡ <br>ì„±ì¥í•˜ê¸° ìœ„í•´ ëŠì„ì—†ì´ ë„ì „í•˜ê³  ë…¸ë ¥í•˜ëŠ”<br><b>ì›¹ ê°œë°œì ì´ì„ ì£¼</b> ì…ë‹ˆë‹¤.

card-front:
  - { icon: "ti-themify-favicon-alt", content: "&nbspClick!" }

contact:
  - { icon: "ti-email", content: "<b>Email. </b>&nbsp&nbsp Lsjnv20@gmail.com" }
  - { icon: "ti-mobile", content: "<b>Phone. </b>&nbsp010.919.6459</p>" }

social:
  - { icon: "ti-github", link: "https://github.com/sjnv20", content: "<b>github.</b>&nbsp github.com/sjnv20" }
  - { icon: "ti-tumblr-alt", link: "https://sj-nv20.tistory.com/", content: "<b>Tistory.</b>&nbsp sj-nv20.tistory.com" }

social_git:
  - { icon: "ti-github", link: "https://github.com/sjnv20", content: "<b>github.</b>  github.com/sjnv20" }

seemore:
  - { icon: "ti-link"}
#-------------------------------
# About (Section and Page)

# About Section
blurb: "ì•ˆë…•í•˜ì„¸ìš” :) ì•ìœ¼ë¡œ ë‚˜ì•„ê°€ëŠ” ê°œë°œì <b>ì´ì„ ì£¼</b> ì…ë‹ˆë‹¤.<br/>ì–´ë””ì„œë“  ë‹¹ë‹¹í•˜ê²Œ ì œ ì—­ëŸ‰ì„ ì–´í•„í•  ìˆ˜ ìˆë„ë¡ ì„±ì¥í•˜ê¸° ìœ„í•´ ì›¹ ê°œë°œê³¼ ê´€ë ¨ëœ ì—¬ëŸ¬ ê¸°ìˆ ë“¤ì„ í•™ìŠµí•˜ê³ ,<br/>ìš”ì•½&ì •ë¦¬í•˜ëŠ” ì¦ê±°ì›€ì„ ê¸°ë°˜ìœ¼ë¡œ ë¸”ë¡œê·¸ì— í•™ìŠµë‚´ìš©ì„ ì •ë¦¬í•˜ëŠ” ìŠµê´€ì„ ë§Œë“¤ì–´ê°€ê³  ìˆìŠµë‹ˆë‹¤.<br/>"

blurb-btn-link: "/about"
blurb-btn-name: Know more..

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Java, color: "#fdb157", value: "90%" }
  - { name: Python, color: "#9473e6", value: "60%" }
  - { name: After Effects, color: "#bdecf6", value: "80%" }
  - { name: Web App, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Junior UX Designer,
      icon: "icon-1.png",
      date: "Jan 2007 - Feb 2009",
      organization: "WEBEX",
    }
  - {
      name: UX & UI Designer,
      icon: "icon-2.png",
      date: "Mar 2009 - Aug 2014",
      organization: "AUGMEDIX",
    }
  - {
      name: Senior UI Designer,
      icon: "icon-3.png",
      date: "Sep 2014 - Present",
      organization: "THEMEFISHER",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: "â–SQLD í•©ê²©",
      date: "2023.10.06",
      organization: "ë°ì´í„°ëª¨ë¸ì˜ ì´í•´ ë° ë¶„ì„<br/> SQL ì´í•´ ë° í™œìš© ì§€ì‹ ìŠµë“",
    }
  - {
      name: "â–[ë©€í‹°ì‡]ì½”ë”©í…ŒìŠ¤íŠ¸ ëŸ¬ë‹í´ë˜ìŠ¤",
      date: "2023.05.03 ~ 2023.06.02",
      organization: "Language: Python <br/><br/> - python ê¸°ë°˜ì˜ ì•Œê³ ë¦¬ì¦˜ ì—­ëŸ‰ ê°•í™” <br/> - ê·¸ë¦¬ë”” ì•Œê³ ë¦¬ì¦˜, ì™„ì „ íƒìƒ‰, ê·¸ë˜í”„ íƒìƒ‰ ë“±ì˜ <br/>&nbsp&nbsp í•™ìŠµì„ í†µí•œ ë¬¸ì œ í•´ê²° ëŠ¥ë ¥ ê°•í™” ",
    }
  - {
      name: "â–[ë©€í‹°ìº í¼ìŠ¤]ë°±ì—”ë“œ ê°œë°œì ì·¨ì—…ìº í”„",
      date: "2022.12.26 ~ 2023.05.09",
      organization: "Language: Java / ë‹¨ìœ„ê¸°ê°„ ìš°ìˆ˜í›ˆë ¨ìƒ ì„ ì • <br/><br/> - Java ê¸°ë°˜ ì›¹ ê°œë°œ í•™ìŠµ <br/> - MongoDB, Spring, Apache Tomcatì„ <br/> &nbsp&nbsp í•™ìŠµí•˜ì—¬ Backend ê¸°ìˆ  ì—­ëŸ‰ ê°•í™”",
    }
  - {
      name: â–ì •ë³´ì²˜ë¦¬ê¸°ì‚¬(í•„ê¸°),
      date: "2022.04.24",
      organization: "í•„ê¸°í•©ê²©",
    }
  - {
      name: â–ë™ì„œëŒ€í•™êµ,
      date: "2019.03 ~ 2023.02",
      organization: "ì „ê³µ : ì •ë³´ë³´ì•ˆí•™ê³¼ <br/> ë³µìˆ˜ì „ê³µ : ì‚¬ì´ë²„ê²½ì°°ë³´ì•ˆì „ê³µ <br/> í•™ì  : 4.22 - ìˆ˜ì„ì¡¸ì—…",
    }
  - {
      name: â–ê²½í˜œì—¬ìê³ ë“±í•™êµ ,
      date: "2016.03 ~ 2019.02",
      organization: "ìì—°ê³„ ê²½í˜œì—¬ê³  ì¡¸ì—…",
    }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: UI Design,
      icon: ti-palette,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }
  - {
      name: UX Design,
      icon: ti-vector,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: true, # Add true to select section
    }
  - {
      name: Interaction Design,
      icon: ti-panel,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
#-------------------------------
# Blog page

blog-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

blog-label:
  - { title: "Tistory", type: "tistory" }
  - { title: "Velog", type: "velog" }

blog-items:
  - image: "assets/images/blog/baek.JPEG"
    url: "https://sj-nv20.tistory.com/13"
    blog-type:
      - type: "tistory"
    memo: "[ë°±ì¤€]Python - 10813:ê³µë°”ê¾¸ê¸°"
    text: Q. 10813 - ê³µ ë°”ê¾¸ê¸° ë¬¸ì œ - ë„í˜„ì´ëŠ” ë°”êµ¬ë‹ˆë¥¼ ì´ Nê°œ ê°€ì§€ê³  ìˆê³ , ê°ê°ì˜ ë°”êµ¬ë‹ˆì—ëŠ” 1ë²ˆë¶€í„° Në²ˆê¹Œì§€ ë²ˆí˜¸ê°€ . . .

  - image: "assets/images/blog/algo.JPEG"
    url: "https://velog.io/@sj-_nv20/Algorithm-%EC%8B%9C%EA%B0%84%EB%B3%B5%EC%9E%A1%EB%8F%84Time-Complexity-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EC%84%A0%ED%83%9D%EC%9D%98"
    blog-type:
      - type: "velog"
    memo: ì‹œê°„ë³µì¡ë„(Time Complexity)
    text: ğŸ¤·ğŸ»â€â™€ï¸ &nbsp;ì‹œê°„ë³µì¡ë„(Time Complexity)ë€? ì•Œê³ ë¦¬ì¦˜ì—ì„œ ì‹œê°„ë³µì¡ë„ëŠ” [ ì£¼ì–´ì§„ ë¬¸ì œë¥¼ í•´ê²°í•˜ê¸° ìœ„í•œ ì—°ì‚° íšŸìˆ˜ ] . . .

  - image: "assets/images/blog/github.JPEG"
    url: "https://sj-nv20.tistory.com/10"
    blog-type:
      - type: "tistory"
    memo: ê¹ƒí—ˆë¸Œ í˜ì´ì§€ 404 ì—ëŸ¬ í•´ê²°ë²•
    text: ğŸ¤·ğŸ»â€â™€ï¸ ì œëŒ€ë¡œ ë§Œë“¤ì—ˆëŠ”ë° 404ê°€ ëœ¬ë‹¤?! ë¶„ëª… ì œëŒ€ë¡œ ë§Œë“¤ì—ˆë‹¤ ìƒê°í–ˆëŠ”ë° 404 í˜ì´ì§€ê°€ ë–´ì„ê²½ìš° ìƒê°í•´ì•¼ í•  ê²ƒì€ ì´ 3 . . .

  - image: "assets/images/blog/post5.JPEG"
    url: "https://sj-nv20.tistory.com/15"
    blog-type:
      - type: "tistory"
    memo: ì •ë³´ì²˜ë¦¬ê¸°ì‚¬ ì‹¤ê¸° ìš”ì•½ì •ë¦¬
    text: 11.ì‘ìš© SW ê¸°ì´ˆ ê¸°ìˆ  í™œìš© * ìš´ì˜ì²´ì œ ì œì–´ ë°©ë²• CLI (Command Line Interface) - ì‚¬ìš©ìê°€ ì§ì ‘ ëª…ë ¹ì–´ ì…ë ¥ . . .
  
  - image: "assets/images/blog/goorm.JPEG"
    url: "https://sj-nv20.tistory.com/11"
    blog-type:
      - type: "tistory"
    memo: "[goorm] Python - ì†Œìˆ˜ì°¾ê¸°"
    text: "Q. ì†Œìˆ˜ì°¾ê¸° ì •ìˆ˜ë¡œë§Œ ì´ë£¨ì–´ì§„ ìˆ˜ì—´Aì— ìˆëŠ” ìˆ˜ë“¤ì„ ì¡°ê±´ì— ë”°ë¼ í•©í•œ ê°’ì„ êµ¬í•˜ê¸°ë¡œ í•œë‹¤. ìˆ˜ì—´ Aì˜ ië²ˆì§¸ ìˆ˜ë¥¼ Ai . . ."

  - image: "assets/images/blog/baek.JPEG"
    url: "https://velog.io/@sj-_nv20/%EB%B0%B1%EC%A4%80-Python-2941-%ED%81%AC%EB%A1%9C%EC%95%84%ED%8B%B0%EC%95%84-%EC%95%8C%ED%8C%8C%EB%B2%B3"
    blog-type:
      - type: "velog"
    memo: "[ë°±ì¤€] 2941 : í¬ë¡œì•„í‹°ì•„ ì•ŒíŒŒë²³"
    text: "ë¬¸ì œ : ì˜ˆì „ì—ëŠ” ìš´ì˜ì²´ì œì—ì„œ í¬ë¡œì•„í‹°ì•„ ì•ŒíŒŒë²³ì„ ì…ë ¥í•  ìˆ˜ê°€ ì—†ì—ˆë‹¤. ë”°ë¼ì„œ, ë‹¤ìŒê³¼ ê°™ì´ í¬ë¡œì•„í‹°ì•„ ì•ŒíŒŒë²³ì„ . . ."
#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: Lsjnv20@gmail.com
